### ISSUE TITLE
release/v2.0.0 - testing notes

### ISSUE THREAD

**Issue by melounek** [EternallLight/cordova-plugin-openwith-ios#24]
@EternallLight good job with the release branch.

Plugin instalation ( #22 ) works correctly with the release branch.

it's not freezing anymore on the sharing-screen when I click on my app in the list, but
- on newest iphone SE (2nd gen.) simulator it hops directly into the app but do not call the `myHandler` func (both text or image)
- on iPhone 11 or iPhone 8 simulators it prompts me to confirm shared text (or description for image) but then it's not redirecting me into the app
 - ( on my real iPhone 5S my app is not in the sharing list for any kind of content )

So basically I was never able enter `myHandler` (`cordova.openwith.addHandler(myHandler)`).

I tested that in my app and also in new empty cordova-app and here is my testing scenario:
```
cordova create cordovatest
cd cordovatest
cordova platform add ios

cordova plugin add https://github.com/EternallLight/cordova-plugin-openwith-ios.git#release/v2.0.0 --variable IOS_URL_SCHEME=duocardssharing

# updated index.js by readme
# updated app-id in config.xml (because of signing in Xcode)
# setup app-groups in Xcode (`group.<YOUR_APP_BUNDLE_ID>.shareextension`) for both app/shareExt targets

# Xcode -> run (on various devices), or:
cordova run iOS
```
hope it helps

**Comment by EternallLight** [comment]
Hi @melounek 
First of all, thank you for sharing this information. 
I believe you couldn't share files on a real devices because you had different iOS versions in deployment target option for you main app and app extension. Check out the updated instructions in the README.md file on the master branch. 
I tested on a real iPhone 7 device and it works now as expected. There are some issues when sharing text from Safari on a simulator but fortunately they do not show up on a real device.

**Comment by EternallLight** [comment]
Yep, I noticed that, too. Will take a look.
Thanks for confirming.

Best regards,
Andrey Grunev

**Comment by EternallLight** [comment]
It does not seem to be possible to fix this issue in the plugin directly.
The cordova-ios platform correction is required
– platforms/ios/cordova/lib/prepare.js. When I worked at Thirdlane, I did
something like a loop over the build targets and determined which is the
main app and which is extension (we had 2 app extensions besides the
sharing one), and did corrections only for the main app.
Unfortunately, cordova still does not support iOS app extensions out of the
box.
I'd really recommend you to run the application from Xcode – not only
because you wouldn't face the bundle identifier override issue during
cordova prepare, it is just much faster.

**Comment by melounek** [comment]
Thanks for checking.
I would like to use only Xcode, but when I update the javascript code, I need to get it into platforms somehow, which does `cordova build` or `cordova prepare`, but these are renaming the identifier.
Or if you know some better workflow how to "prepare" the updated JS, let me know.

Otherwise this should be better documented in the 10th point in the readme (the renaming or using loop-script you mentioned).

**Comment by EternallLight** [comment]
As a quick solution, you can correct your app build process and add to the
last step copying the built stuff form ./www to ./platfforms/ios/www

**Comment by melounek** [comment]
will try, thanks

**Comment by melounek** [comment]
> Unfortunately, cordova still does not support iOS app extensions out of the box.

Looks like the issue will be fixed soon. Now it's in cordova-ios version `6.0.0-dev` https://github.com/apache/cordova-ios/pull/820
